In [3]:
import numpy as np

In [4]:
mylist = [1, 2, 3]

In [11]:
np.array(mylist)

array([1, 2, 3])

In [9]:
type(mylist)

list

In [12]:
mylist


[1, 2, 3]

In [14]:
myarr = np.array(mylist)

In [15]:
myarr

array([1, 2, 3])

In [16]:
type(myarr)

numpy.ndarray

In [17]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [18]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [20]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
np.arange(0 ,10, 2)

array([0, 2, 4, 6, 8])

In [27]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [30]:
np.zeros((2, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [31]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [32]:
np.linspace(0 ,10, 3)

array([ 0.,  5., 10.])

In [33]:
len(np.linspace(0, 5, 21))

21

In [34]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [36]:
np.random.rand(5, 2)

array([[0.4417552 , 0.93686907],
       [0.34088827, 0.93985439],
       [0.48272821, 0.68958666],
       [0.73540715, 0.85365029],
       [0.16172992, 0.59632237]])

In [38]:
np.random.randn(10)

array([-0.8220222 , -1.15282559,  0.7993948 ,  1.635671  , -0.00428502,
        0.29647006, -0.36051501, -2.62214288,  0.3765706 , -1.43129052])

In [39]:
np.random.randn(2, 3)

array([[-0.86548793, -0.14242316, -0.47923913],
       [-1.06773145,  0.27234078, -0.59560582]])

In [42]:
np.random.randint(1, 101, 10)

array([39, 50, 92, 18, 93, 43, 36, 68, 40, 69])

In [44]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [45]:
arr = np.arange(0 ,25)

In [46]:
arr.reshape(5, 5)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])